-- Create products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  app_name TEXT NOT NULL,
  short_description TEXT NOT NULL,
  long_description TEXT,
  target_audience TEXT,
  example_hooks TEXT, -- JSON array of example hooks
  example_hashtags TEXT, -- JSON array of example hashtags
  user_id UUID DEFAULT gen_random_uuid() -- For tracking, not auth
);

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
CREATE POLICY "Allow public view products" ON public.products
  FOR SELECT TO public
  USING (true);

CREATE POLICY "Allow public insert products" ON public.products
  FOR INSERT TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update products" ON public.products
  FOR UPDATE TO public
  USING (true);

CREATE POLICY "Allow public delete products" ON public.products
  FOR DELETE TO public
  USING (true); 