-- Migration script to update the database for ReelPost

-- 1. Add 'gif' to video_type enum
ALTER TYPE video_type ADD VALUE 'gif';

-- 2. Update RLS policies to work without authentication

-- Backgrounds table policies
DROP POLICY IF EXISTS "Users can delete their own backgrounds" ON backgrounds;
DROP POLICY IF EXISTS "Users can insert their own backgrounds" ON backgrounds;
DROP POLICY IF EXISTS "Users can update their own backgrounds" ON backgrounds;

CREATE POLICY "Allow public insert backgrounds" ON backgrounds
    FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Allow public update backgrounds" ON backgrounds
    FOR UPDATE TO public
    USING (true);

CREATE POLICY "Allow public delete backgrounds" ON backgrounds
    FOR DELETE TO public
    USING (true);

-- Generated videos table policies
DROP POLICY IF EXISTS "Users can insert their own generated videos" ON generated_videos;
DROP POLICY IF EXISTS "Users can update their own generated videos" ON generated_videos;
DROP POLICY IF EXISTS "Users can view their own generated videos" ON generated_videos;
DROP POLICY IF EXISTS "Users can delete their own generated videos" ON generated_videos;

CREATE POLICY "Allow public operations on generated_videos" ON generated_videos
    FOR ALL TO public
    USING (true)
    WITH CHECK (true);

-- Templates table policies
DROP POLICY IF EXISTS "Users can insert their own templates" ON templates;
DROP POLICY IF EXISTS "Users can update their own templates" ON templates;
DROP POLICY IF EXISTS "Users can delete their own templates" ON templates;

CREATE POLICY "Allow public insert templates" ON templates
    FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Allow public update templates" ON templates
    FOR UPDATE TO public
    USING (true);

CREATE POLICY "Allow public delete templates" ON templates
    FOR DELETE TO public
    USING (true);

-- Sound table policies
DROP POLICY IF EXISTS "Users can insert their own sounds" ON sound;
DROP POLICY IF EXISTS "Users can update their own sounds" ON sound;
DROP POLICY IF EXISTS "Users can delete their own sounds" ON sound;

CREATE POLICY "Allow public insert sounds" ON sound
    FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Allow public update sounds" ON sound
    FOR UPDATE TO public
    USING (true);

CREATE POLICY "Allow public delete sounds" ON sound
    FOR DELETE TO public
    USING (true);

-- Demo table policies
DROP POLICY IF EXISTS "Allow users to insert their own demos" ON demo;
DROP POLICY IF EXISTS "Users can update their own demos" ON demo;
DROP POLICY IF EXISTS "Allow users to view their own demos" ON demo;
DROP POLICY IF EXISTS "Allow users to delete their own demos" ON demo;

CREATE POLICY "Allow public insert demos" ON demo
    FOR INSERT TO public
    WITH CHECK (true);

CREATE POLICY "Allow public update demos" ON demo
    FOR UPDATE TO public
    USING (true);

CREATE POLICY "Allow public view demos" ON demo
    FOR SELECT TO public
    USING (true);

CREATE POLICY "Allow public delete demos" ON demo
    FOR DELETE TO public
    USING (true);

-- 3. Verify the changes
SELECT 
    t.typname AS enum_name,
    e.enumlabel AS enum_value
FROM pg_type t 
JOIN pg_enum e ON t.oid = e.enumtypid
WHERE t.typname = 'video_type'
ORDER BY e.enumsortorder; 

-- Create products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  app_name TEXT NOT NULL,
  short_description TEXT NOT NULL,
  long_description TEXT,
  target_audience TEXT,
  example_hooks TEXT, -- JSON array of example hooks
  example_hashtags TEXT, -- JSON array of example hashtags
  user_id UUID DEFAULT gen_random_uuid()
);

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
CREATE POLICY "Allow public view products" ON public.products
  FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert products" ON public.products
  FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public update products" ON public.products
  FOR UPDATE TO public USING (true);

CREATE POLICY "Allow public delete products" ON public.products
  FOR DELETE TO public USING (true);